apiVersion: apps/v1
kind: Deployment

metadata:
  name: inference-api
spec:
  replicas: 3

  selector:
    matchLabels:
      app: inference-api

  template:
    metadata:
      labels:
        app: inference-api

    spec: 
      containers:
        - name: inference-api
          image: ai-infra-api:v1
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "256Mi"
--- 
apiVersion: v1
kind: Service

metadata:
  name: inference-api-service

spec:
  selector:
    app: inference-api

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
